image: python:3.9

stages:
  - deploy_to_s3

variables:
  AWS_DEFAULT_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET: elice-artsy-bucket

deploy_to_s3:
  stage: deploy_to_s3
  script:
    - echo "debugging environment variables"
    - echo "AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID"
    - echo "S3_BUCKET $S3_BUCKET"
    - apt-get update -y
    - apt-get install -y zip
    - zip -r my-express-app.zip .
    - pip install awscli
    - aws s3 cp my-express-app.zip s3://$S3_BUCKET/dev/my-express-app.zip
  only:
    - dev
