image: python:3.9

stages:
  - deploy_to_s3

variables:
  AWS_DEFAULT_REGION: ap-northeast-2
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET: elice-artsy-bucket
  S3_ZIP: my-express-app.zip

deploy_to_s3:
  stage: deploy_to_s3
  script:
    - echo "debugging environment variables"
    - echo "AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID"
    - echo "S3_BUCKET $S3_BUCKET"
    - apt-get update -y
    - apt-get install -y zip
    - zip -r $S3_ZIP .
    - pip install awscli
    - aws s3 cp $S3_ZIP s3://$S3_BUCKET/dev/$S3_ZIP
    - aws deploy create-deployment
      --application-name artsy-codedeploy
      --deployment-config-name CodeDeployDefault.OneAtATime
      --deployment-group-name dev
      --s3-location bucket=$S3_BUCKET,bundleType=zip,key=dev/$S3_ZIP
  only:
    - dev
